apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fws-cluster
  region: ap-northeast-1

vpc:
  subnets:
    public:
      ap-northeast-1a: { id: subnet-ae2efde6 }
      ap-northeast-1c: { id: subnet-7fdfd224 }
      ap-northeast-1d: { id: subnet-9321fbb8 }

nodeGroups:
  - name: ng-1-workers
    minSize: 1
    maxSize: 2
    desiredCapacity: 2
    instancesDistribution:
      instanceTypes: ["t3.medium", "t3.large"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
      spotInstancePools: 2
    privateNetworking: false
  - name: ng-2-builders
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    instancesDistribution:
      instanceTypes: ["t3.large", "t3.xlarge"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
      spotInstancePools: 2
    privateNetworking: false
    iam:
      withAddonPolicies:
        imageBuilder: true
