apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: argo-rollouts
  namespace: flux-system
spec:
  url: https://argoproj.github.io/argo-helm
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-rollouts
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: argo-rollouts
      sourceRef:
        kind: HelmRepository
        name: argo-rollouts
        namespace: flux-system
      version: "2.37.6"
  values:
    installCRDs: true
